name: learning GitHub Actions
run-name: I am learing GitHub Actions!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run helloWorld.js
        run: node helloWorld.js
