name: Saludo usando variables y secretos
run-name: ¡Estoy aprendiendo a usar variables y secretos!
on: 
  workflow_dispatch
env:
  WEEKDAY: Wednesday
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      GREETING: Hello World
    steps:
      - name: Saludo Variables
        run: echo "$GREETING, ${{vars.NOMBRE}}. Hoy es ${{env.WEEKDAY}}!"
  saludo-secreto:
    runs-on: ubuntu-latest
    env:
      GREETING: Hello World
    steps:
      - name: Saludo secreto
        run: echo "$GREETING, ${{vars.NOMBRE}}. Tu password es ${{secrets.PASSWORD}}!"
